# Generated by Django 2.2 on 2019-05-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_away',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_home',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='address',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='email',
            field=models.EmailField(max_length=191),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='firstName',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='lastName',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='password',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='username',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=191),
        ),
        migrations.AlterField(
            model_name='player',
            name='firstName',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastName',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='player',
            name='province',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize',
            field=models.TextField(max_length=191),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rule',
            field=models.TextField(max_length=191),
        ),
    ]
