# Generated by Django 2.2 on 2019-05-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='type',
            new_name='sex',
        ),
    ]
