# Generated by Django 2.1.7 on 2019-05-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_join',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_join', to='goodgames.Team'),
        ),
    ]
