# Generated by Django 2.1.7 on 2019-05-07 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0002_player_team_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='picture',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.FileField(upload_to='media'),
        ),
    ]
