# Generated by Django 2.2 on 2019-05-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0003_auto_20190504_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='password1',
            new_name='password_confirm',
        ),
        migrations.RemoveField(
            model_name='player',
            name='password2',
        ),
    ]
