# Generated by Django 2.2 on 2019-05-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0004_auto_20190504_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='password_confirm',
        ),
    ]
