# Generated by Django 2.1.7 on 2019-05-08 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0005_player_team_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='player_create',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='player_create', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='player_join',
            field=models.ManyToManyField(related_name='player_join', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='player_team',
            field=models.ManyToManyField(related_name='player_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
