# Generated by Django 2.2 on 2019-05-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0005_auto_20190504_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_away',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_home',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(),
        ),
    ]
