# Generated by Django 2.2 on 2019-05-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0007_auto_20190504_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(default='1999-01-01'),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone1',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone2',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='province',
            field=models.CharField(default='Bangkok', max_length=100),
        ),
    ]
