# Generated by Django 2.2 on 2019-05-04 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0008_auto_20190504_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='player',
            name='password2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
