# Generated by Django 2.1.7 on 2019-05-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0008_auto_20190516_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='team_join',
            field=models.ManyToManyField(related_name='team_join', to='goodgames.Team'),
        ),
    ]
