# Generated by Django 2.2 on 2019-05-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0009_auto_20190504_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_admin',
        ),
    ]
