# Generated by Django 2.1.7 on 2019-05-17 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0009_auto_20190516_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='organizer',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
