# Generated by Django 2.1.7 on 2019-05-19 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0010_auto_20190518_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goodgames.Categories'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goodgames.Organizer'),
        ),
    ]
