# Generated by Django 2.1.7 on 2019-05-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0011_auto_20190519_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rule',
            field=models.TextField(null=True),
        ),
    ]
