# Generated by Django 2.2 on 2019-05-04 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0011_auto_20190504_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='value',
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goodgames.Team'),
        ),
    ]
